use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: "http://localhost:8080/"
  image_proxy: true
  http_protocol_version: "1.1"
  method: "POST"

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  default_theme: simple
  theme_args:
    simple_style: dark

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "auto"
  formats:
    - html
    - json

engines:
  # AI & Technology focused engines
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: false
    
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    
  - name: bing
    engine: bing
    shortcut: bi
    
  - name: github
    engine: github
    shortcut: gh
    
  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    
  - name: arxiv
    engine: arxiv
    shortcut: ar
    categories: science
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'
    
  # Chinese search engines
  - name: baidu
    engine: baidu
    shortcut: bd
    language: zh_CN
    
  # Developer tools
  - name: npm
    engine: npm
    shortcut: npm
    disabled: false
    
  - name: pypi
    engine: pypi
    shortcut: pypi
    disabled: false

redis:
  url: redis://redis:6379/1

outgoing:
  request_timeout: 10.0
  max_request_timeout: 20.0
  useragent_suffix: "LUXOR-AI-CUA"
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'